[2017-03-13 16:41:42,820 root CRITICAL] Exception:Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != d053100c86e7e09d717b04d5bc320df6015c8912 (server)
[2017-03-13 16:41:42,821 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 724, in Login
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 853, in _GetServiceContent
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/VmomiSupport.py", line 543, in <lambda>
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1235, in InvokeMethod
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1320, in GetConnection
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 897, in _VerifyThumbprint
 ThumbprintMismatchException: Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != d053100c86e7e09d717b04d5bc320df6015c8912 (server)

